[theme]
primaryColor = "#5A381E"      # Banana yellow (main accent)
backgroundColor = "#FFEA99"   # Creamy pale yellow background
secondaryBackgroundColor = "#FFF5C8"  # Slightly deeper banana cream for sidebars/cards
textColor = "#3E2C23"         # Deep cocoa brown for readability
font = "Space Grotesk"

# Optional interactive colors
linkColor = "#5A381E"         # Rich deep brown for links/buttons
hoverColor = "#7B4A28"        # Warmer, slightly lighter brown for hover/focus states




[server]
headless = true
